// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Backend.Infrastructure.Persistence;

#nullable disable

namespace Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307160000_AddDeviceCredentials")]
    partial class AddDeviceCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal. This Designer exists only to expose the
            // [Migration] attribute so EF Core discovers and applies this
            // migration. BuildTargetModel is not consulted when applying
            // migrations at runtime — Up()/Down() operations run directly.
        }
    }
}
